import {
  COMPARISON_RESULTS,
  LOCAL_RESULTS,
  EXPORT_RESULTS,
  OCR_RESULTS,
  REGION_OCR_RESULTS,
  TRANSLATION_RESULTS
} from './operationResults.js'

export const SEMANTIC_CATEGORY = Object.freeze({
  ACKNOWLEDGEMENT: 'acknowledgement',
  PERSISTENT_INFORMATION: 'persistent-information',
  PROGRESS: 'progress'
})

/**
 * Classification is pre-computed at design time using the ADR-011 decision tree.
 * For each result type the following questions are answered:
 *   1. Is the core meaning ongoing progress?        → PROGRESS
 *   2. Is this merely an acknowledgement?           → ACKNOWLEDGEMENT
 *   3. Does it require interpretation?              → PERSISTENT_INFORMATION
 *   4. Would losing it cause information loss?      → PERSISTENT_INFORMATION
 *   5. Fallback                                     → ACKNOWLEDGEMENT
 */
const CATEGORY_MAP = Object.freeze({
  [EXPORT_RESULTS.COMPLETED]: SEMANTIC_CATEGORY.ACKNOWLEDGEMENT,
  [EXPORT_RESULTS.FAILED]: SEMANTIC_CATEGORY.ACKNOWLEDGEMENT,

  [COMPARISON_RESULTS.COMPLETED]: SEMANTIC_CATEGORY.PERSISTENT_INFORMATION,
  [COMPARISON_RESULTS.FAILED]: SEMANTIC_CATEGORY.PERSISTENT_INFORMATION,
  [COMPARISON_RESULTS.PROGRESS]: SEMANTIC_CATEGORY.PROGRESS,

  [OCR_RESULTS.COMPLETED]: SEMANTIC_CATEGORY.ACKNOWLEDGEMENT,
  [OCR_RESULTS.FAILED]: SEMANTIC_CATEGORY.ACKNOWLEDGEMENT,
  [OCR_RESULTS.LANGUAGE_MISSING]: SEMANTIC_CATEGORY.ACKNOWLEDGEMENT,
  [OCR_RESULTS.PROGRESS]: SEMANTIC_CATEGORY.PROGRESS,

  [REGION_OCR_RESULTS.COMPLETED]: SEMANTIC_CATEGORY.ACKNOWLEDGEMENT,
  [REGION_OCR_RESULTS.FAILED]: SEMANTIC_CATEGORY.ACKNOWLEDGEMENT,
  [REGION_OCR_RESULTS.NO_TEXT]: SEMANTIC_CATEGORY.ACKNOWLEDGEMENT,
  [REGION_OCR_RESULTS.PROGRESS]: SEMANTIC_CATEGORY.PROGRESS,

  [TRANSLATION_RESULTS.PROGRESS]: SEMANTIC_CATEGORY.PROGRESS,
  [TRANSLATION_RESULTS.PARTIAL]: SEMANTIC_CATEGORY.PERSISTENT_INFORMATION,

  [LOCAL_RESULTS.PANE_EMPTY]: SEMANTIC_CATEGORY.ACKNOWLEDGEMENT,
  [LOCAL_RESULTS.PAGE_OCR_COMPLETE]: SEMANTIC_CATEGORY.ACKNOWLEDGEMENT,
  [LOCAL_RESULTS.BLOCK_LOADING]: SEMANTIC_CATEGORY.PROGRESS,
  [LOCAL_RESULTS.BLOCK_ERROR]: SEMANTIC_CATEGORY.PERSISTENT_INFORMATION
})

/**
 * Classifies an Operation Result into a Semantic Category.
 * Classification is type-only — does not inspect result data.
 * Unknown types fall back to ACKNOWLEDGEMENT.
 *
 * @param {object} result - Operation Result with a `type` field
 * @returns {string} Semantic Category
 */
export function classify(result) {
  return CATEGORY_MAP[result?.type] ?? SEMANTIC_CATEGORY.ACKNOWLEDGEMENT
}
