export const LIVE_CAPTION_SETTINGS_KEYS = Object.freeze({
  ENABLED: 'LIVE_CAPTION_ENABLED',
  QUALITY_PROFILE: 'LIVE_CAPTION_QUALITY_PROFILE',
  DISPLAY_MODE: 'LIVE_CAPTION_DISPLAY_MODE',
  CACHE_MAX_ITEMS: 'LIVE_CAPTION_CACHE_MAX_ITEMS',
  CACHE_MAX_BYTES: 'LIVE_CAPTION_CACHE_MAX_BYTES',
  STT_PROVIDER: 'LIVE_CAPTION_STT_PROVIDER',
  RETRY_LIMIT: 'LIVE_CAPTION_RETRY_LIMIT'
});

export default LIVE_CAPTION_SETTINGS_KEYS;
