import { CONFIG } from '@/shared/config/config.js';

export const LIVE_CAPTION_DEFAULTS = Object.freeze({
  ENABLED: CONFIG.LIVE_CAPTION_ENABLED,
  QUALITY_PROFILE: CONFIG.LIVE_CAPTION_QUALITY_PROFILE,
  CACHE_MAX_ITEMS: CONFIG.LIVE_CAPTION_CACHE_MAX_ITEMS,
  CACHE_MAX_BYTES: CONFIG.LIVE_CAPTION_CACHE_MAX_BYTES,
  STT_PROVIDER: CONFIG.LIVE_CAPTION_STT_PROVIDER,
  RETRY_LIMIT: CONFIG.LIVE_CAPTION_RETRY_LIMIT,
  OPENAI_API_KEY_SETTING: 'OPENAI_API_KEY'
});

export default LIVE_CAPTION_DEFAULTS;
