import { MessageActions } from '@/shared/messaging/core/MessageActions.js';

export const LIVE_CAPTION_ACTIONS = Object.freeze({
  START_REQUEST: MessageActions.LIVE_CAPTION_START_REQUEST,
  PRIVACY_NOTICE: MessageActions.LIVE_CAPTION_PRIVACY_NOTICE,
  PRIVACY_ACCEPTED: MessageActions.LIVE_CAPTION_PRIVACY_ACCEPTED,
  START: MessageActions.LIVE_CAPTION_START,
  STOP: MessageActions.LIVE_CAPTION_STOP,
  AUDIO_CHUNK: MessageActions.LIVE_CAPTION_AUDIO_CHUNK,
  STT_RESULT: MessageActions.LIVE_CAPTION_STT_RESULT,
  TRANSLATE_REQUEST: MessageActions.LIVE_CAPTION_TRANSLATE_REQUEST,
  TRANSLATE_RESULT: MessageActions.LIVE_CAPTION_TRANSLATE_RESULT,
  VIDEO_CHANGED: MessageActions.LIVE_CAPTION_VIDEO_CHANGED,
  SEEK: MessageActions.LIVE_CAPTION_SEEK,
  STATUS: MessageActions.LIVE_CAPTION_STATUS,
  ERROR: MessageActions.LIVE_CAPTION_ERROR,
  CLEAR_CACHE: MessageActions.LIVE_CAPTION_CLEAR_CACHE,
  RUNTIME_START: MessageActions.LIVE_CAPTION_RUNTIME_START,
  RUNTIME_STOP: MessageActions.LIVE_CAPTION_RUNTIME_STOP,
  RUNTIME_STATUS: MessageActions.LIVE_CAPTION_RUNTIME_STATUS,
  RUNTIME_PAUSE: MessageActions.LIVE_CAPTION_RUNTIME_PAUSE,
  RUNTIME_RESUME: MessageActions.LIVE_CAPTION_RUNTIME_RESUME
});

export default LIVE_CAPTION_ACTIONS;
