// src/utils/languages.js

export const languageList = [
  { name: "English", code: "en-US", promptName: "English" },
  { name: "Persian", code: "fa-IR", promptName: "Persian" },
  { name: "German", code: "de-DE", promptName: "German" },
  { name: "French", code: "fr-FR", promptName: "French" },
  {
    name: "Chinese (Simplified)",
    code: "zh-CN",
    promptName: "Chinese (Simplified)",
  },
  { name: "Spanish", code: "es-ES", promptName: "Spanish" },
  { name: "Hindi", code: "hi-IN", promptName: "Hindi" },
  { name: "Arabic", code: "ar-SA", promptName: "Arabic" },
  { name: "Bengali", code: "bn-BD", promptName: "Bengali" },
  { name: "Portuguese", code: "pt-PT", promptName: "Portuguese" },
  { name: "Russian", code: "ru-RU", promptName: "Russian" },
  { name: "Japanese", code: "ja-JP", promptName: "Japanese" },
  { name: "Urdu", code: "ur-PK", promptName: "Urdu" },
  { name: "Indonesian", code: "id-ID", promptName: "Indonesian" },
  { name: "Italian", code: "it-IT", promptName: "Italian" },
  { name: "Swahili", code: "sw-KE", promptName: "Swahili" },
  { name: "Marathi", code: "mr-IN", promptName: "Marathi" },
  { name: "Telugu", code: "te-IN", promptName: "Telugu" },
  { name: "Tamil", code: "ta-IN", promptName: "Tamil" },
  { name: "Turkish", code: "tr-TR", promptName: "Turkish" },
  { name: "Vietnamese", code: "vi-VN", promptName: "Vietnamese" },
  { name: "Korean", code: "ko-KR", promptName: "Korean" },
  { name: "Thai", code: "th-TH", promptName: "Thai" },
  { name: "Malay", code: "ms-MY", promptName: "Malay" },
  { name: "Polish", code: "pl-PL", promptName: "Polish" },
  { name: "Dutch", code: "nl-NL", promptName: "Dutch" },
  { name: "Filipino", code: "fil-PH", promptName: "Filipino" },
  { name: "Ukrainian", code: "uk-UA", promptName: "Ukrainian" },
  { name: "Romanian", code: "ro-RO", promptName: "Romanian" },
  { name: "Greek", code: "el-GR", promptName: "Greek" },
  { name: "Czech", code: "cs-CZ", promptName: "Czech" },
  { name: "Hungarian", code: "hu-HU", promptName: "Hungarian" },
  { name: "Swedish", code: "sv-SE", promptName: "Swedish" },
  { name: "Norwegian", code: "no-NO", promptName: "Norwegian" },
  { name: "Danish", code: "da-DK", promptName: "Danish" },
  { name: "Finnish", code: "fi-FI", promptName: "Finnish" },
  { name: "Hebrew", code: "he-IL", promptName: "Hebrew" },
  { name: "Afrikaans", code: "af-ZA", promptName: "Afrikaans" },
  { name: "Albanian", code: "sq-AL", promptName: "Albanian" },
  { name: "Bulgarian", code: "bg-BG", promptName: "Bulgarian" },
  { name: "Catalan", code: "ca-ES", promptName: "Catalan" },
  { name: "Croatian", code: "hr-HR", promptName: "Croatian" },
  { name: "Estonian", code: "et-EE", promptName: "Estonian" },
  { name: "Latvian", code: "lv-LV", promptName: "Latvian" },
  { name: "Lithuanian", code: "lt-LT", promptName: "Lithuanian" },
  { name: "Slovak", code: "sk-SK", promptName: "Slovak" },
  { name: "Slovenian", code: "sl-SI", promptName: "Slovenian" },
  { name: "Serbian", code: "sr-RS", promptName: "Serbian" },
  { name: "Malayalam", code: "ml-IN", promptName: "Malayalam" },
  { name: "Kannada", code: "kn-IN", promptName: "Kannada" },
  { name: "Odia", code: "or-IN", promptName: "Odia" },
  { name: "Punjabi", code: "pa-IN", promptName: "Punjabi" },
  { name: "Sinhala", code: "si-LK", promptName: "Sinhala" },
  { name: "Nepali", code: "ne-NP", promptName: "Nepali" },
  { name: "Azerbaijani", code: "az-AZ", promptName: "Azerbaijani" },
  { name: "Belarusian", code: "be-BY", promptName: "Belarusian" },
  { name: "Kazakh", code: "kk-KZ", promptName: "Kazakh" },
  { name: "Uzbek", code: "uz-UZ", promptName: "Uzbek" },
  { name: "Pashto", code: "ps-AF", promptName: "Pashto" },
  { name: "Tagalog", code: "tl-PH", promptName: "Tagalog" },

  // Cebuano فاقد کد استاندارد IETF است، ممکن است در برخی از موتورهای TTS پشتیبانی نشود.
  // در صورت نیاز می‌توانید از یک کد مرتبط دیگر یا یک کد عمومی مانند 'en-US' استفاده کنید.
  { name: "Cebuano", code: "en-US", promptName: "Cebuano" },

  { name: "English (UK)", code: "en-GB", promptName: "English" },
  { name: "German (Austria)", code: "de-AT", promptName: "German" },
  { name: "French (Canada)", code: "fr-CA", promptName: "French" },
];
