/**
 * Live-dubbing control-plane and bounded transport constants.
 *
 * Provider execution remains feature-local; only its public action and timing
 * fences are shared across extension contexts.
 */
export const LIVE_DUBBING_OWNER = 'live-dubbing';
export const LIVE_DUBBING_STORAGE_KEY = '__translateItLiveDubbingSession';
export const LIVE_DUBBING_OUTCOME_STORAGE_KEY = '__translateItLiveDubbingTerminalOutcome';
export const LIVE_DUBBING_PROVIDER_ID = 'gemini';
export const LIVE_DUBBING_OPENAI_PROVIDER_ID = 'openai';
export const LIVE_DUBBING_PROVIDER_IDS = Object.freeze([
  LIVE_DUBBING_PROVIDER_ID,
  LIVE_DUBBING_OPENAI_PROVIDER_ID,
]);

export const LIVE_DUBBING_LEASE_REASONS = Object.freeze([
  'USER_MEDIA',
  'AUDIO_PLAYBACK',
]);

export const LIVE_DUBBING_CAPTURE_STAGES = Object.freeze({
  OFFSCREEN_PREPARE: 'OFFSCREEN_PREPARE',
  GET_MEDIA_STREAM_ID: 'GET_MEDIA_STREAM_ID',
  OFFSCREEN_GET_USER_MEDIA: 'OFFSCREEN_GET_USER_MEDIA',
});

export const LIVE_DUBBING_STORAGE_STATE = Object.freeze({
  ABSENT: 'ABSENT',
  PRESENT: 'PRESENT',
  UNREADABLE: 'UNREADABLE',
});

export const LIVE_DUBBING_OUTCOME_STORAGE_STATE = Object.freeze({
  ABSENT: 'ABSENT',
  PRESENT: 'PRESENT',
  READ_FAILED: 'READ_FAILED',
  WRITE_FAILED: 'WRITE_FAILED',
});

const publicLiveDubbingStatus = {
  PREPARING_CAPTURE: 'PREPARING_CAPTURE',
  CONNECTING_PROVIDER: 'CONNECTING_PROVIDER',
  RUNNING: 'RUNNING',
  STOPPING: 'STOPPING',
  ERROR: 'ERROR',
};

// Legacy consumers can still read the old internal name, but it is not an
// enumerable/public status and is never accepted in a descriptor.
Object.defineProperty(publicLiveDubbingStatus, 'CAPTURING', {
  value: 'CAPTURING',
  enumerable: false,
});

export const LIVE_DUBBING_STATUS = Object.freeze(publicLiveDubbingStatus);

/**
 * CAPTURING is an offscreen implementation state, not a public descriptor
 * state. Keep it separate so it cannot accidentally be exposed to UI callers.
 */
export const LIVE_DUBBING_INTERNAL_STATUS = Object.freeze({
  CAPTURING: 'CAPTURING',
});

export const LIVE_DUBBING_ACTIONS = Object.freeze({
  START: 'START_LIVE_DUBBING',
  STOP: 'STOP_LIVE_DUBBING',
  GET_STATUS: 'GET_LIVE_DUBBING_STATUS',
  SET_ORIGINAL_VOLUME: 'SET_LIVE_DUBBING_ORIGINAL_VOLUME',
  SET_ORIGINAL_VOLUME_OFFSCREEN: 'LIVE_DUBBING_SET_ORIGINAL_VOLUME',
  GET_ORIGINAL_VOLUME: 'GET_LIVE_DUBBING_ORIGINAL_VOLUME',
  GET_ORIGINAL_VOLUME_OFFSCREEN: 'LIVE_DUBBING_GET_ORIGINAL_VOLUME',
  SET_DUBBED_VOLUME: 'SET_LIVE_DUBBING_DUBBED_VOLUME',
  SET_DUBBED_VOLUME_OFFSCREEN: 'LIVE_DUBBING_SET_DUBBED_VOLUME',
  GET_DUBBED_VOLUME: 'GET_LIVE_DUBBING_DUBBED_VOLUME',
  GET_DUBBED_VOLUME_OFFSCREEN: 'LIVE_DUBBING_GET_DUBBED_VOLUME',
  START_ALIAS: 'LIVE_DUBBING_START',
  STOP_ALIAS: 'LIVE_DUBBING_STOP',
  GET_STATUS_ALIAS: 'LIVE_DUBBING_GET_STATUS',
  PREPARE: 'LIVE_DUBBING_PREPARE',
  CONSUME: 'LIVE_DUBBING_CONSUME',
  CONNECT_PROVIDER: 'LIVE_DUBBING_CONNECT_PROVIDER',
  DISPOSE: 'LIVE_DUBBING_DISPOSE',
  STATUS: 'LIVE_DUBBING_STATUS',
  TERMINAL: 'LIVE_DUBBING_TERMINAL',
  TERMINAL_OUTCOME: 'LIVE_DUBBING_TERMINAL_OUTCOME',
  REQUEST_PROVIDER_BOOTSTRAP: 'LIVE_DUBBING_REQUEST_PROVIDER_BOOTSTRAP',
  VALIDATE_CREDENTIAL: 'LIVE_DUBBING_VALIDATE_CREDENTIAL',
  TRANSLATED_TRANSCRIPT: 'LIVE_DUBBING_TRANSLATED_TRANSCRIPT',
  ORIGINAL_TRANSCRIPT: 'LIVE_DUBBING_ORIGINAL_TRANSCRIPT',
  // Keep the legacy names as value aliases while the dedicated transport
  // actions remain the canonical names used by the live-dubbing pipeline.
  TRANSCRIPT: 'LIVE_DUBBING_TRANSLATED_TRANSCRIPT',
  TRANSCRIPT_CLEAR: 'LIVE_DUBBING_TRANSCRIPT_CLEAR',
  CLEAR_TRANSCRIPT: 'LIVE_DUBBING_TRANSCRIPT_CLEAR',
  ORIGINAL_TRANSCRIPT_CLEAR: 'LIVE_DUBBING_TRANSCRIPT_CLEAR',
});

export const LIVE_DUBBING_TRANSLATED_TRANSCRIPT_KIND = 'translated';
export const LIVE_DUBBING_ORIGINAL_TRANSCRIPT_KIND = 'source';
export const LIVE_DUBBING_TRANSLATED_TRANSCRIPT_MAX_LENGTH = 2_048;
export const LIVE_DUBBING_ORIGINAL_TRANSCRIPT_MAX_LENGTH = 2_048;

export const LIVE_DUBBING_OFFSCREEN_ACTIONS = Object.freeze([
  LIVE_DUBBING_ACTIONS.PREPARE,
  LIVE_DUBBING_ACTIONS.CONSUME,
  LIVE_DUBBING_ACTIONS.CONNECT_PROVIDER,
  LIVE_DUBBING_ACTIONS.STATUS,
  LIVE_DUBBING_ACTIONS.DISPOSE,
  LIVE_DUBBING_ACTIONS.SET_ORIGINAL_VOLUME_OFFSCREEN,
  LIVE_DUBBING_ACTIONS.GET_ORIGINAL_VOLUME_OFFSCREEN,
  LIVE_DUBBING_ACTIONS.SET_DUBBED_VOLUME_OFFSCREEN,
  LIVE_DUBBING_ACTIONS.GET_DUBBED_VOLUME_OFFSCREEN,
]);

export const LIVE_DUBBING_TIMEOUTS = Object.freeze({
  START: 30_000,
  STOP: 10_000,
  STATUS: 5_000,
  SETUP: 10_000,
});

export const LIVE_DUBBING_START_TIMEOUT = LIVE_DUBBING_TIMEOUTS.START;
export const LIVE_DUBBING_STOP_TIMEOUT = LIVE_DUBBING_TIMEOUTS.STOP;
export const LIVE_DUBBING_STATUS_TIMEOUT = LIVE_DUBBING_TIMEOUTS.STATUS;
export const LIVE_DUBBING_SETUP_TIMEOUT = LIVE_DUBBING_TIMEOUTS.SETUP;

export const LIVE_DUBBING_ACTION_TIMEOUTS = Object.freeze({
  [LIVE_DUBBING_ACTIONS.START]: LIVE_DUBBING_TIMEOUTS.START,
  [LIVE_DUBBING_ACTIONS.START_ALIAS]: LIVE_DUBBING_TIMEOUTS.START,
  [LIVE_DUBBING_ACTIONS.STOP]: LIVE_DUBBING_TIMEOUTS.STOP,
  [LIVE_DUBBING_ACTIONS.STOP_ALIAS]: LIVE_DUBBING_TIMEOUTS.STOP,
  [LIVE_DUBBING_ACTIONS.GET_STATUS]: LIVE_DUBBING_TIMEOUTS.STATUS,
  [LIVE_DUBBING_ACTIONS.GET_STATUS_ALIAS]: LIVE_DUBBING_TIMEOUTS.STATUS,
  [LIVE_DUBBING_ACTIONS.SET_ORIGINAL_VOLUME]: LIVE_DUBBING_TIMEOUTS.STATUS,
  [LIVE_DUBBING_ACTIONS.GET_ORIGINAL_VOLUME]: LIVE_DUBBING_TIMEOUTS.STATUS,
  [LIVE_DUBBING_ACTIONS.GET_ORIGINAL_VOLUME_OFFSCREEN]: LIVE_DUBBING_TIMEOUTS.STATUS,
  [LIVE_DUBBING_ACTIONS.SET_DUBBED_VOLUME]: LIVE_DUBBING_TIMEOUTS.STATUS,
  [LIVE_DUBBING_ACTIONS.GET_DUBBED_VOLUME]: LIVE_DUBBING_TIMEOUTS.STATUS,
  [LIVE_DUBBING_ACTIONS.GET_DUBBED_VOLUME_OFFSCREEN]: LIVE_DUBBING_TIMEOUTS.STATUS,
  [LIVE_DUBBING_ACTIONS.PREPARE]: LIVE_DUBBING_TIMEOUTS.SETUP,
  [LIVE_DUBBING_ACTIONS.CONSUME]: LIVE_DUBBING_TIMEOUTS.SETUP,
  [LIVE_DUBBING_ACTIONS.CONNECT_PROVIDER]: LIVE_DUBBING_TIMEOUTS.SETUP,
  [LIVE_DUBBING_ACTIONS.DISPOSE]: LIVE_DUBBING_TIMEOUTS.SETUP,
  [LIVE_DUBBING_ACTIONS.REQUEST_PROVIDER_BOOTSTRAP]: LIVE_DUBBING_TIMEOUTS.SETUP,
  [LIVE_DUBBING_ACTIONS.VALIDATE_CREDENTIAL]: LIVE_DUBBING_TIMEOUTS.SETUP,
});

export const LIVE_DUBBING_ACTION_TIMEOUT_MAP = LIVE_DUBBING_ACTION_TIMEOUTS;

export const LIVE_DUBBING_OFFSCREEN_ACKS = Object.freeze({
  READY: 'READY',
  MEDIA_ACQUIRED: 'MEDIA_ACQUIRED',
  PROVIDER_READY: 'PROVIDER_READY',
  DISPOSED: 'DISPOSED',
});

/**
 * Audio transport limits are intentionally small and explicit. They bound
 * startup pressure without making normal translated output lossy.
 */
export const LIVE_DUBBING_AUDIO_LIMITS = Object.freeze({
  INPUT_PENDING_MAX_MS: 500,
  INPUT_PENDING_RETAIN_MS: 200,
  INPUT_MAX_BUFFERED_AMOUNT: 64 * 1024,
});

export const LIVE_DUBBING_INPUT_PENDING_MAX_MS = LIVE_DUBBING_AUDIO_LIMITS.INPUT_PENDING_MAX_MS;
export const LIVE_DUBBING_INPUT_PENDING_RETAIN_MS = LIVE_DUBBING_AUDIO_LIMITS.INPUT_PENDING_RETAIN_MS;
export const LIVE_DUBBING_INPUT_MAX_BUFFERED_AMOUNT = LIVE_DUBBING_AUDIO_LIMITS.INPUT_MAX_BUFFERED_AMOUNT;

export const LIVE_DUBBING_DESCRIPTOR_FIELDS = Object.freeze([
  'sessionId',
  'tabId',
  'providerId',
  'targetLanguage',
  'status',
  'startedAt',
  'lastError',
  'eventSequence',
]);

/**
 * Provider audio paths. `pcm` pumps capture frames through the local
 * TabAudioPipeline/PcmOutputPlayer graphs and the provider's sendAudio
 * contract. `media-stream` hands the retained capture MediaStream to a
 * provider that consumes and plays audio itself; no local PCM graphs are
 * built. The mode is declared per provider in the registry and resolved
 * by the controller — never inferred, never hard-coded per provider id.
 */
export const LIVE_DUBBING_AUDIO_MODES = Object.freeze({
  PCM: 'pcm',
  MEDIA_STREAM: 'media-stream',
});
