import { describe, it, expect } from 'vitest';
import {
  LiveCaptionFeature,
  LIVE_CAPTION_ACTIONS,
  LIVE_CAPTION_SETTINGS_KEYS,
  LIVE_CAPTION_DEFAULTS,
  LIVE_CAPTION_SESSION_STATES,
  LIVE_CAPTION_CLEANUP_REASONS,
  createLiveCaptionSessionSnapshot,
  createVideoCaptionSessionSnapshot,
  PageLiveCaptionSession,
  VideoCaptionSession,
  LiveCaptionSessionManager,
  BaseSTTProvider,
  useLiveCaptionStore,
  ActiveVideoDetector,
  VideoFingerprint,
  LiveCaptionCacheKeys,
  LIVE_CAPTION_CACHE_DB_NAME,
  LIVE_CAPTION_CACHE_DB_VERSION,
  LIVE_CAPTION_CACHE_STORE_NAMES,
  LIVE_CAPTION_CACHE_STORE_DEFINITIONS,
  createLiveCaptionSessionCacheKey,
  createLiveCaptionVideoCacheKey,
  createLiveCaptionSegmentCacheKey,
  createLiveCaptionTranslatedSegmentCacheKey,
  createLiveCaptionCacheSchema,
  applyLiveCaptionCacheSchema,
  createLiveCaptionCacheUnavailableError,
  openLiveCaptionCacheDatabase,
  LiveCaptionCache,
  LiveCaptionTranscriptRepository,
  LiveCaptionTranslationRepository,
  normalizeLiveCaptionTranscriptSegment,
  normalizeLiveCaptionTranslationSegment,
  LiveCaptionOffscreenBridge,
  LiveCaptionCaptureCoordinator,
  LIVE_CAPTION_CAPTURE_STATES,
  LIVE_CAPTION_OFFSCREEN_ERROR_CODES,
  LIVE_CAPTION_OFFSCREEN_MESSAGE_TYPES,
  LIVE_CAPTION_TRANSLATION_CONTEXT,
  LIVE_CAPTION_TRANSLATION_MODE,
  LIVE_CAPTION_TRANSLATION_ERROR_CODES,
  createLiveCaptionTranscriptSegmentInput,
  createLiveCaptionTranslationRequestMetadata,
  createLiveCaptionTranslationRequest,
  createLiveCaptionTranslatedCaptionSegment,
  normalizeLiveCaptionTranslationError,
  createLiveCaptionStartCaptureRequest,
  createLiveCaptionStopCaptureRequest,
  createLiveCaptionStatusRequest,
  createLiveCaptionFinalizedChunkMessage,
  createLiveCaptionCaptureErrorMessage,
  createLiveCaptionOffscreenSnapshotResponse,
  createLiveCaptionFailClosedResponse,
  normalizeLiveCaptionOffscreenResponse,
  STT_PROVIDER_STATUS,
  STT_PROVIDER_ERROR_CODES,
  normalizeSTTResult,
  createSTTProviderStatus,
  createSTTProviderError,
  isRetryableSTTError,
  normalizeSTTProviderError,
  STT_PROVIDER_IDS,
  STT_PROVIDER_MODES,
  STT_PROVIDER_CAPABILITIES,
  STT_PROVIDER_MANIFEST,
  getDefaultSTTProviderId,
  getSTTProviderDefinition,
  getAvailableSTTProviders,
  isSTTProviderSupported,
  STTProviderFactory,
  OpenAIWhisperProvider
} from './index.js';
import { MessageActions } from '@/shared/messaging/core/MessageActions.js';
import { CONFIG } from '@/shared/config/config.js';

describe('live-caption feature shell', () => {
  it('exports constants and contracts from the public entry point', () => {
    expect(LiveCaptionFeature.actions).toBe(LIVE_CAPTION_ACTIONS);
    expect(LIVE_CAPTION_ACTIONS.START_REQUEST).toBe(MessageActions.LIVE_CAPTION_START_REQUEST);
    expect(LIVE_CAPTION_SETTINGS_KEYS.ENABLED).toBe('LIVE_CAPTION_ENABLED');
    expect(LIVE_CAPTION_DEFAULTS.ENABLED).toBe(CONFIG.LIVE_CAPTION_ENABLED);
    expect(LIVE_CAPTION_DEFAULTS.OPENAI_API_KEY_SETTING).toBe('OPENAI_API_KEY');
    expect(LIVE_CAPTION_SESSION_STATES.IDLE).toBe('idle');
    expect(LIVE_CAPTION_CLEANUP_REASONS.STOP).toBe('stop');
    expect(LiveCaptionFeature.store).toBe(useLiveCaptionStore);
    expect(LiveCaptionFeature.cleanupReasons).toBe(LIVE_CAPTION_CLEANUP_REASONS);
    expect(LiveCaptionFeature.contracts.createLiveCaptionSessionSnapshot).toBe(createLiveCaptionSessionSnapshot);
    expect(LiveCaptionFeature.contracts.createVideoCaptionSessionSnapshot).toBe(createVideoCaptionSessionSnapshot);
    expect(ActiveVideoDetector).toBe(LiveCaptionFeature.contracts.ActiveVideoDetector);
    expect(VideoFingerprint).toBe(LiveCaptionFeature.contracts.VideoFingerprint);
    expect(LiveCaptionCacheKeys).toBe(LiveCaptionFeature.contracts.LiveCaptionCacheKeys);
    expect(LIVE_CAPTION_CACHE_DB_NAME).toBe(LiveCaptionFeature.contracts.LIVE_CAPTION_CACHE_DB_NAME);
    expect(LIVE_CAPTION_CACHE_DB_VERSION).toBe(LiveCaptionFeature.contracts.LIVE_CAPTION_CACHE_DB_VERSION);
    expect(LIVE_CAPTION_CACHE_STORE_NAMES).toBe(LiveCaptionFeature.contracts.LIVE_CAPTION_CACHE_STORE_NAMES);
    expect(LIVE_CAPTION_CACHE_STORE_DEFINITIONS).toBe(LiveCaptionFeature.contracts.LIVE_CAPTION_CACHE_STORE_DEFINITIONS);
    expect(createLiveCaptionSessionCacheKey).toBe(LiveCaptionFeature.contracts.createLiveCaptionSessionCacheKey);
    expect(createLiveCaptionVideoCacheKey).toBe(LiveCaptionFeature.contracts.createLiveCaptionVideoCacheKey);
    expect(createLiveCaptionSegmentCacheKey).toBe(LiveCaptionFeature.contracts.createLiveCaptionSegmentCacheKey);
    expect(createLiveCaptionTranslatedSegmentCacheKey).toBe(LiveCaptionFeature.contracts.createLiveCaptionTranslatedSegmentCacheKey);
    expect(createLiveCaptionCacheSchema).toBe(LiveCaptionFeature.contracts.createLiveCaptionCacheSchema);
    expect(applyLiveCaptionCacheSchema).toBe(LiveCaptionFeature.contracts.applyLiveCaptionCacheSchema);
    expect(createLiveCaptionCacheUnavailableError).toBe(LiveCaptionFeature.contracts.createLiveCaptionCacheUnavailableError);
    expect(openLiveCaptionCacheDatabase).toBe(LiveCaptionFeature.contracts.openLiveCaptionCacheDatabase);
    expect(LiveCaptionCache).toBe(LiveCaptionFeature.contracts.LiveCaptionCache);
    expect(LiveCaptionTranscriptRepository).toBe(LiveCaptionFeature.contracts.LiveCaptionTranscriptRepository);
    expect(LiveCaptionTranslationRepository).toBe(LiveCaptionFeature.contracts.LiveCaptionTranslationRepository);
    expect(normalizeLiveCaptionTranscriptSegment).toBe(LiveCaptionFeature.contracts.normalizeLiveCaptionTranscriptSegment);
    expect(normalizeLiveCaptionTranslationSegment).toBe(LiveCaptionFeature.contracts.normalizeLiveCaptionTranslationSegment);
    expect(LiveCaptionOffscreenBridge).toBe(LiveCaptionFeature.contracts.LiveCaptionOffscreenBridge);
    expect(LiveCaptionCaptureCoordinator).toBe(LiveCaptionFeature.contracts.LiveCaptionCaptureCoordinator);
    expect(LIVE_CAPTION_CAPTURE_STATES).toBe(LiveCaptionFeature.contracts.LIVE_CAPTION_CAPTURE_STATES);
    expect(LIVE_CAPTION_OFFSCREEN_ERROR_CODES).toBe(LiveCaptionFeature.contracts.LIVE_CAPTION_OFFSCREEN_ERROR_CODES);
    expect(LIVE_CAPTION_OFFSCREEN_MESSAGE_TYPES).toBe(LiveCaptionFeature.contracts.LIVE_CAPTION_OFFSCREEN_MESSAGE_TYPES);
    expect(createLiveCaptionStartCaptureRequest).toBe(LiveCaptionFeature.contracts.createLiveCaptionStartCaptureRequest);
    expect(createLiveCaptionStopCaptureRequest).toBe(LiveCaptionFeature.contracts.createLiveCaptionStopCaptureRequest);
    expect(createLiveCaptionStatusRequest).toBe(LiveCaptionFeature.contracts.createLiveCaptionStatusRequest);
    expect(createLiveCaptionFinalizedChunkMessage).toBe(LiveCaptionFeature.contracts.createLiveCaptionFinalizedChunkMessage);
    expect(createLiveCaptionCaptureErrorMessage).toBe(LiveCaptionFeature.contracts.createLiveCaptionCaptureErrorMessage);
    expect(createLiveCaptionOffscreenSnapshotResponse).toBe(LiveCaptionFeature.contracts.createLiveCaptionOffscreenSnapshotResponse);
    expect(createLiveCaptionFailClosedResponse).toBe(LiveCaptionFeature.contracts.createLiveCaptionFailClosedResponse);
    expect(normalizeLiveCaptionOffscreenResponse).toBe(LiveCaptionFeature.contracts.normalizeLiveCaptionOffscreenResponse);
    expect(LIVE_CAPTION_TRANSLATION_CONTEXT).toBe(LiveCaptionFeature.contracts.LIVE_CAPTION_TRANSLATION_CONTEXT);
    expect(LIVE_CAPTION_TRANSLATION_MODE).toBe(LiveCaptionFeature.contracts.LIVE_CAPTION_TRANSLATION_MODE);
    expect(LIVE_CAPTION_TRANSLATION_ERROR_CODES).toBe(LiveCaptionFeature.contracts.LIVE_CAPTION_TRANSLATION_ERROR_CODES);
    expect(createLiveCaptionTranscriptSegmentInput).toBe(LiveCaptionFeature.contracts.createLiveCaptionTranscriptSegmentInput);
    expect(createLiveCaptionTranslationRequestMetadata).toBe(LiveCaptionFeature.contracts.createLiveCaptionTranslationRequestMetadata);
    expect(createLiveCaptionTranslationRequest).toBe(LiveCaptionFeature.contracts.createLiveCaptionTranslationRequest);
    expect(createLiveCaptionTranslatedCaptionSegment).toBe(LiveCaptionFeature.contracts.createLiveCaptionTranslatedCaptionSegment);
    expect(normalizeLiveCaptionTranslationError).toBe(LiveCaptionFeature.contracts.normalizeLiveCaptionTranslationError);
    expect(BaseSTTProvider).toBe(LiveCaptionFeature.contracts.BaseSTTProvider);
    expect(STT_PROVIDER_STATUS).toBe(LiveCaptionFeature.contracts.STT_PROVIDER_STATUS);
    expect(STT_PROVIDER_ERROR_CODES).toBe(LiveCaptionFeature.contracts.STT_PROVIDER_ERROR_CODES);
    expect(normalizeSTTResult).toBe(LiveCaptionFeature.contracts.normalizeSTTResult);
    expect(createSTTProviderStatus).toBe(LiveCaptionFeature.contracts.createSTTProviderStatus);
    expect(createSTTProviderError).toBe(LiveCaptionFeature.contracts.createSTTProviderError);
    expect(isRetryableSTTError).toBe(LiveCaptionFeature.contracts.isRetryableSTTError);
    expect(normalizeSTTProviderError).toBe(LiveCaptionFeature.contracts.normalizeSTTProviderError);
    expect(STT_PROVIDER_IDS).toBe(LiveCaptionFeature.contracts.STT_PROVIDER_IDS);
    expect(STT_PROVIDER_MODES).toBe(LiveCaptionFeature.contracts.STT_PROVIDER_MODES);
    expect(STT_PROVIDER_CAPABILITIES).toBe(LiveCaptionFeature.contracts.STT_PROVIDER_CAPABILITIES);
    expect(STT_PROVIDER_MANIFEST).toBe(LiveCaptionFeature.contracts.STT_PROVIDER_MANIFEST);
    expect(getDefaultSTTProviderId).toBe(LiveCaptionFeature.contracts.getDefaultSTTProviderId);
    expect(getSTTProviderDefinition).toBe(LiveCaptionFeature.contracts.getSTTProviderDefinition);
    expect(getAvailableSTTProviders).toBe(LiveCaptionFeature.contracts.getAvailableSTTProviders);
    expect(isSTTProviderSupported).toBe(LiveCaptionFeature.contracts.isSTTProviderSupported);
    expect(STTProviderFactory).toBe(LiveCaptionFeature.contracts.STTProviderFactory);
    expect(OpenAIWhisperProvider).toBe(LiveCaptionFeature.contracts.OpenAIWhisperProvider);
  });

  it('exports session contracts without runtime wiring', () => {
    expect(PageLiveCaptionSession).toBeTypeOf('function');
    expect(VideoCaptionSession).toBeTypeOf('function');
    expect(LiveCaptionSessionManager).toBeTypeOf('function');
    expect(BaseSTTProvider).toBeTypeOf('function');
    expect(STTProviderFactory).toBeTypeOf('function');
    expect(OpenAIWhisperProvider).toBeTypeOf('function');
  });
});
