import { LIVE_CAPTION_ACTIONS } from './constants/liveCaptionActions.js';
import { LIVE_CAPTION_SETTINGS_KEYS } from './constants/liveCaptionSettings.js';
import { LIVE_CAPTION_DEFAULTS } from './constants/liveCaptionDefaults.js';
import { LIVE_CAPTION_SESSION_STATES } from './constants/liveCaptionSessionStates.js';
import { useLiveCaptionStore } from './stores/liveCaption.js';
import {
  LIVE_CAPTION_CLEANUP_REASONS,
  createLiveCaptionErrorState,
  createLiveCaptionSessionId,
  createLiveCaptionSessionSnapshot,
  createVideoCaptionSessionSnapshot,
  ActiveVideoDetector,
  collectActiveVideoCandidates,
  rankActiveVideoCandidates,
  selectActiveVideoCandidate,
  VideoFingerprint,
  describeVideoFingerprint,
  createVideoFingerprint,
  LiveCaptionCacheKeys,
  createLiveCaptionVideoCacheKey,
  createLiveCaptionSegmentCacheKey,
  createLiveCaptionTranslatedSegmentCacheKey,
  PageLiveCaptionSession,
  VideoCaptionSession,
  LiveCaptionSessionManager
} from './core/index.js';
import { LiveCaptionCache } from './cache/LiveCaptionCache.js';
import { LiveCaptionTranscriptRepository } from './cache/LiveCaptionTranscriptRepository.js';
import { LiveCaptionTranslationRepository } from './cache/LiveCaptionTranslationRepository.js';
import {
  LiveCaptionBackgroundController,
  LiveCaptionOffscreenBridge,
  LIVE_CAPTION_CAPTURE_STATES,
  LIVE_CAPTION_OFFSCREEN_ERROR_CODES,
  LIVE_CAPTION_OFFSCREEN_MESSAGE_TYPES,
  LiveCaptionCaptureCoordinator,
  createLiveCaptionStartCaptureRequest,
  createLiveCaptionStopCaptureRequest,
  createLiveCaptionStatusRequest,
  createLiveCaptionFinalizedChunkMessage,
  createLiveCaptionCaptureErrorMessage,
  createLiveCaptionOffscreenSnapshotResponse,
  createLiveCaptionFailClosedResponse,
  normalizeLiveCaptionOffscreenResponse,
  LIVE_CAPTION_TRANSLATION_CONTEXT,
  LIVE_CAPTION_TRANSLATION_MODE,
  LIVE_CAPTION_TRANSLATION_ERROR_CODES,
  normalizeLiveCaptionTranscriptSegment,
  createLiveCaptionTranscriptSegmentInput,
  createLiveCaptionTranslationRequestMetadata,
  createLiveCaptionTranslationRequest,
  createLiveCaptionTranslatedCaptionSegment,
  normalizeLiveCaptionTranslationError,
  LiveCaptionTranslationAdapter
} from './background/index.js';
import { LiveCaptionContentController } from './content/LiveCaptionContentController.js';
import {
  BaseSTTProvider,
  STT_PROVIDER_STATUS,
  STT_PROVIDER_ERROR_CODES,
  normalizeSTTResult,
  createSTTProviderStatus,
  createSTTProviderError,
  isRetryableSTTError,
  normalizeSTTProviderError,
  STT_PROVIDER_IDS,
  STT_PROVIDER_MODES,
  STT_PROVIDER_CAPABILITIES,
  STT_PROVIDER_MANIFEST,
  getDefaultSTTProviderId,
  getSTTProviderDefinition,
  getAvailableSTTProviders,
  isSTTProviderSupported,
  STTProviderFactory,
  OpenAIWhisperProvider
} from './stt/index.js';

export { LIVE_CAPTION_ACTIONS } from './constants/liveCaptionActions.js';
export { LIVE_CAPTION_SETTINGS_KEYS } from './constants/liveCaptionSettings.js';
export { LIVE_CAPTION_DEFAULTS } from './constants/liveCaptionDefaults.js';
export { LIVE_CAPTION_SESSION_STATES } from './constants/liveCaptionSessionStates.js';
export { useLiveCaptionStore } from './stores/liveCaption.js';
export {
  BaseSTTProvider,
  STT_PROVIDER_STATUS,
  STT_PROVIDER_ERROR_CODES,
  normalizeSTTResult,
  createSTTProviderStatus,
  createSTTProviderError,
  isRetryableSTTError,
  normalizeSTTProviderError,
  STT_PROVIDER_IDS,
  STT_PROVIDER_MODES,
  STT_PROVIDER_CAPABILITIES,
  STT_PROVIDER_MANIFEST,
  getDefaultSTTProviderId,
  getSTTProviderDefinition,
  getAvailableSTTProviders,
  isSTTProviderSupported,
  STTProviderFactory,
  OpenAIWhisperProvider
} from './stt/index.js';
export {
  LIVE_CAPTION_CLEANUP_REASONS,
  createLiveCaptionErrorState,
  createLiveCaptionSessionId,
  createLiveCaptionSessionSnapshot,
  createVideoCaptionSessionSnapshot,
  ActiveVideoDetector,
  collectActiveVideoCandidates,
  rankActiveVideoCandidates,
  selectActiveVideoCandidate,
  VideoFingerprint,
  describeVideoFingerprint,
  createVideoFingerprint,
  LiveCaptionCacheKeys,
  createLiveCaptionVideoCacheKey,
  createLiveCaptionSegmentCacheKey,
  createLiveCaptionTranslatedSegmentCacheKey,
  PageLiveCaptionSession,
  VideoCaptionSession,
  LiveCaptionSessionManager
} from './core/index.js';
export { LiveCaptionCache } from './cache/LiveCaptionCache.js';
export { LiveCaptionTranscriptRepository } from './cache/LiveCaptionTranscriptRepository.js';
export { LiveCaptionTranslationRepository } from './cache/LiveCaptionTranslationRepository.js';
export {
  LiveCaptionBackgroundController,
  LiveCaptionOffscreenBridge,
  LIVE_CAPTION_CAPTURE_STATES,
  LIVE_CAPTION_OFFSCREEN_ERROR_CODES,
  LIVE_CAPTION_OFFSCREEN_MESSAGE_TYPES,
  LiveCaptionCaptureCoordinator,
  createLiveCaptionStartCaptureRequest,
  createLiveCaptionStopCaptureRequest,
  createLiveCaptionStatusRequest,
  createLiveCaptionFinalizedChunkMessage,
  createLiveCaptionCaptureErrorMessage,
  createLiveCaptionOffscreenSnapshotResponse,
  createLiveCaptionFailClosedResponse,
  normalizeLiveCaptionOffscreenResponse,
  LIVE_CAPTION_TRANSLATION_CONTEXT,
  LIVE_CAPTION_TRANSLATION_MODE,
  LIVE_CAPTION_TRANSLATION_ERROR_CODES,
  normalizeLiveCaptionTranscriptSegment,
  createLiveCaptionTranscriptSegmentInput,
  createLiveCaptionTranslationRequestMetadata,
  createLiveCaptionTranslationRequest,
  createLiveCaptionTranslatedCaptionSegment,
  normalizeLiveCaptionTranslationError,
  LiveCaptionTranslationAdapter
} from './background/index.js';
export { LiveCaptionContentController } from './content/LiveCaptionContentController.js';

export const LiveCaptionFeature = Object.freeze({
  actions: LIVE_CAPTION_ACTIONS,
  settings: LIVE_CAPTION_SETTINGS_KEYS,
  defaults: LIVE_CAPTION_DEFAULTS,
  states: LIVE_CAPTION_SESSION_STATES,
  cleanupReasons: LIVE_CAPTION_CLEANUP_REASONS,
  store: useLiveCaptionStore,
  contracts: {
    createLiveCaptionErrorState,
    createLiveCaptionSessionId,
    createLiveCaptionSessionSnapshot,
    createVideoCaptionSessionSnapshot,
    ActiveVideoDetector,
    collectActiveVideoCandidates,
    rankActiveVideoCandidates,
    selectActiveVideoCandidate,
    VideoFingerprint,
    describeVideoFingerprint,
    createVideoFingerprint,
    LiveCaptionCacheKeys,
    createLiveCaptionVideoCacheKey,
    createLiveCaptionSegmentCacheKey,
    createLiveCaptionTranslatedSegmentCacheKey,
    PageLiveCaptionSession,
    VideoCaptionSession,
    LiveCaptionSessionManager,
    BaseSTTProvider,
    LiveCaptionCache,
    LiveCaptionTranscriptRepository,
    LiveCaptionTranslationRepository,
    LiveCaptionBackgroundController,
    LiveCaptionOffscreenBridge,
    LIVE_CAPTION_CAPTURE_STATES,
    LIVE_CAPTION_OFFSCREEN_ERROR_CODES,
    LIVE_CAPTION_OFFSCREEN_MESSAGE_TYPES,
    LiveCaptionCaptureCoordinator,
    createLiveCaptionStartCaptureRequest,
    createLiveCaptionStopCaptureRequest,
    createLiveCaptionStatusRequest,
    createLiveCaptionFinalizedChunkMessage,
    createLiveCaptionCaptureErrorMessage,
    createLiveCaptionOffscreenSnapshotResponse,
    createLiveCaptionFailClosedResponse,
    normalizeLiveCaptionOffscreenResponse,
    LIVE_CAPTION_TRANSLATION_CONTEXT,
    LIVE_CAPTION_TRANSLATION_MODE,
    LIVE_CAPTION_TRANSLATION_ERROR_CODES,
    normalizeLiveCaptionTranscriptSegment,
    createLiveCaptionTranscriptSegmentInput,
    createLiveCaptionTranslationRequestMetadata,
    createLiveCaptionTranslationRequest,
    createLiveCaptionTranslatedCaptionSegment,
    normalizeLiveCaptionTranslationError,
    LiveCaptionTranslationAdapter,
    LiveCaptionContentController,
    STT_PROVIDER_STATUS,
    STT_PROVIDER_ERROR_CODES,
    normalizeSTTResult,
    createSTTProviderStatus,
    createSTTProviderError,
    isRetryableSTTError,
    normalizeSTTProviderError,
    STT_PROVIDER_IDS,
    STT_PROVIDER_MODES,
    STT_PROVIDER_CAPABILITIES,
    STT_PROVIDER_MANIFEST,
    getDefaultSTTProviderId,
    getSTTProviderDefinition,
    getAvailableSTTProviders,
    isSTTProviderSupported,
    STTProviderFactory,
    OpenAIWhisperProvider
  }
});

export default LiveCaptionFeature;
